# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: Metrics
on:
  schedule: [{cron: "0 */3 * * *"}]
  workflow_dispatch:
  push: {branches: ["pre-release"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: metrics-update
      cancel-in-progress: true
    steps:
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/lockfiles') }}
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Kolkata
          optimize: css, xml
          user: nihalxkumar

          base: activity,metadata
          
          plugin_habits_charts_type: classic
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          
          
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, languages-graphs, editors-graphs
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_days: 180
          plugin_wakatime_languages_ignored: markdown, plaintext, text, xml, yaml, JSON
          
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_timestamps: true
          
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent

